### ISSUE TITLE
PendingPR removes all labels

### ISSUE THREAD

**Issue by vbuberen** [dandua98/PendingPR#8]
It seems that there is an issue with labels removal - PendingPR removes not only its own label, but also other labels from the issue as well. 
Here is one of such PRs: https://github.com/ChuckerTeam/chucker/issues/155

I think it is not how it supposed to work and should only remove its own labels.

P.S. Thanks a lot for such a cool thing.

**Comment by vbuberen** [comment]
Hi @dandua98 
I see that you closed the issue and would like to find out if it is something that you don't plan to investigate/fix or it is fixed already?

**Comment by dandua98** [comment]
Oops I didn't mean to close this, I actually never noticed this issue before. Will resolve with an actual fix soon, thanks for opening this!

**Comment by dandua98** [comment]
Closed this issue although I still need to deploy new changes since I don't have CI setup right now

**Comment by vbuberen** [comment]
Awesome, thanks. 

As to CI - do you need help with it? I would gladly help or share experience if needed.

**Comment by dandua98** [comment]
Thanks, I have auto-deploy setup now but my but other than that won't really be adding new features in the near future to justify adding tests and have a CI actually. Just don't have the bandwidth to work on this right now.
